### ISSUE TITLE
Pay using saved card/already a customer

### ISSUE THREAD

**Issue by priyagr** [srikanthonl/ngx-braintree#88]
Hi,
I want to give an option in html to pay via saved card if a customer has already made a payment with braintree. How can I give that option in frontend?
Please help me out to achieve this.

**Comment by selected-pixel-jameson** [comment]
You need to use the vaulted option and configure it within BrainTree as well. 
```
<ngx-braintree 
  [clientTokenURL]="'api/braintree/getclienttoken'" 
  [createPurchaseURL]="'api/braintree/createpurchase'"
  (paymentStatus)="onPaymentStatus($event)"
  [chargeAmount]="55.55"
  ...
  [enablePaypalVault] = "true">
</ngx-braintree>
```

**Comment by mathieu-bour** [comment]
As described here (https://developers.braintreepayments.com/reference/request/client-token/generate/php#customer_id), you should include the vaulted `customerId` when generating the client token.

**Comment by westlakem** [comment]
@mathieu-bour In order to do that, you need to pass a custom function into `[getClientToken]` instead of using [clientTokenUrl], which is currently broken #82

**Comment by srikanthonl** [comment]
@westlakem using clientTokenURL or using getClientToken has got nothing to do to generate a client token based on a customerid because the client token is generated on your server side. So, if you use clientTokenURL or you use getClientToken you would actually be calling the same generate client token server api endpoint of yours. So, @priyagr as @mathieu-bour said you need to generate the clienttoken using the customerid after which ngx-braintree automatically shows the customer's saved payment information.
